profile: dev

# environments
dev:
  jwt_secret: secret to test
  data_host: localhost
  tpv_user: http://localhost:8081
  tpv_core: http://localhost:8082
prod:
  jwt_secret: secret-${JWT_SECRET}
  data_host: ${MONGODB_URI}
  tpv_user: https://betca-tpv-user.herokuapp.com
  tpv_core: https://betca-tpv-core.herokuapp.com
