name: Python Customer Support - Tests

on:
  push:
    branches:
      - 'develop'
      - 'release-*'

jobs:

  test:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
      - name: Start Mongodb
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - name: Test
        run: coverage run -m unittest discover tests
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
      - name: Coverage Report
        run: coverage xml
      - name: SonarCloud Scan
        if: success()
        uses: SonarSource/sonarcloud-github-action@v1.2 # file: sonar-project.properties
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Slack WebHook
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,author,commit,author,workflow, # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required